### Feature Agenda — GET ALL / GET ONE
### Leyenda: SIN AUTH (sin middleware JWT / sin autenticación)
@baseUrl = http://localhost:4000
@id = 1

# @name getAllAgendas
GET {{baseUrl}}/api/agendas

###

# @name getOneAgenda
GET {{baseUrl}}/api/agendas/{{id}}
