### Feature ClinicalRecord — UPDATE (PUT) / UPDATE (PATCH)
### Leyenda: JWT + RBAC (login como admin + Authorization: Bearer)
@baseUrl = http://localhost:4000

# @name loginAdmin
POST {{baseUrl}}/api/session/login
Content-Type: application/json

{
  "identifier": "admin",
  "password": "Admin123!"
}

@token = {{loginAdmin.response.body.$.access_token}}

###
@id = 1

# @name updateClinicalRecordPut
PUT {{baseUrl}}/api/clinical-records/{{id}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Historia clínica — Ana Pérez",
  "description": "Antecedente de hipertensión arterial controlada",
  "status": "active"
}

###

# @name updateClinicalRecordPatch
PATCH {{baseUrl}}/api/clinical-records/{{id}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "description": "Alergia a la penicilina"
}
