### Feature Authorization — UPDATE (PUT) / UPDATE (PATCH)
### Leyenda: JWT + RBAC (login como admin + Authorization: Bearer)
@baseUrl = http://localhost:4000

# @name loginAdmin
POST {{baseUrl}}/api/session/login
Content-Type: application/json

{
  "identifier": "admin",
  "password": "Admin123!"
}

@token = {{loginAdmin.response.body.$.access_token}}

###
@id = 1

# @name updateAuthorizationPut
PUT {{baseUrl}}/api/authorizations/{{id}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "AUT-00012345",
  "description": "Autorización EPS Sura (renovada)",
  "status": "active"
}

###

# @name updateAuthorizationPatch
PATCH {{baseUrl}}/api/authorizations/{{id}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "description": "Autorización medicina prepagada"
}
