### Feature Appointment — CREATE
### Leyenda: SIN AUTH (sin middleware JWT / sin autenticación)
@baseUrl = http://localhost:4000

# @name createAppointment
POST {{baseUrl}}/api/appointments
Content-Type: application/json

{
  "agenda_id": 1,
  "patient_id": 1,
  "start_date": "2026-10-05T08:00:00",
  "end_date": "2026-10-05T08:30:00",
  "reason": "Consulta de control",
  "status": "active"
}
