### Feature Specialty — CREATE
### Leyenda: JWT + RBAC (login como admin + Authorization: Bearer)
@baseUrl = http://localhost:4000

# @name loginAdmin
POST {{baseUrl}}/api/session/login
Content-Type: application/json

{
  "identifier": "admin",
  "password": "Admin123!"
}

@token = {{loginAdmin.response.body.$.access_token}}

###

# @name createSpecialty
POST {{baseUrl}}/api/specialties
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Cardiología",
  "description": "Diagnóstico y tratamiento de enfermedades del corazón",
  "status": "active"
}
