### Feature Doctor — UPDATE (PUT) / UPDATE (PATCH)
### Leyenda: JWT + RBAC (login como admin + Authorization: Bearer)
@baseUrl = http://localhost:4000

# @name loginAdmin
POST {{baseUrl}}/api/session/login
Content-Type: application/json

{
  "identifier": "admin",
  "password": "Admin123!"
}

@token = {{loginAdmin.response.body.$.access_token}}

###
@id = 1

# @name updateDoctorPut
PUT {{baseUrl}}/api/doctors/{{id}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Dr. Carlos Gómez Ruiz",
  "description": "Médico de consulta externa, 11 años de experiencia",
  "status": "active"
}

###

# @name updateDoctorPatch
PATCH {{baseUrl}}/api/doctors/{{id}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "description": "Descripción parcial"
}
