### Feature Doctor — CREATE
### Leyenda: JWT + RBAC (login como admin + Authorization: Bearer)
@baseUrl = http://localhost:4000

# @name loginAdmin
POST {{baseUrl}}/api/session/login
Content-Type: application/json

{
  "identifier": "admin",
  "password": "Admin123!"
}

@token = {{loginAdmin.response.body.$.access_token}}

###

# @name createDoctor
POST {{baseUrl}}/api/doctors
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Dr. Carlos Gómez",
  "description": "Médico de consulta externa, 10 años de experiencia",
  "status": "active"
}
