### Feature Encounter — UPDATE (PUT) / UPDATE (PATCH)
### Leyenda: JWT + RBAC (login como admin + Authorization: Bearer)
@baseUrl = http://localhost:4000

# @name loginAdmin
POST {{baseUrl}}/api/session/login
Content-Type: application/json

{
  "identifier": "admin",
  "password": "Admin123!"
}

@token = {{loginAdmin.response.body.$.access_token}}

###
@id = 1

# @name updateEncounterPut
PUT {{baseUrl}}/api/encounters/{{id}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "start_date": "2026-10-05T08:00:00",
  "end_date": "2026-10-05T08:25:00",
  "total": 90000,
  "state": "completed",
  "observations": "Se ordenan exámenes de control",
  "status": "active"
}

###

# @name updateEncounterPatch
PATCH {{baseUrl}}/api/encounters/{{id}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "observations": "Se ajusta tratamiento y se programa control en 30 días"
}
