### Feature Encounter — GET ALL / GET ONE
### Leyenda: JWT + RBAC (login como admin + Authorization: Bearer)
@baseUrl = http://localhost:4000

# @name loginAdmin
POST {{baseUrl}}/api/session/login
Content-Type: application/json

{
  "identifier": "admin",
  "password": "Admin123!"
}

@token = {{loginAdmin.response.body.$.access_token}}

###
@id = 1

# @name getAllEncounters
GET {{baseUrl}}/api/encounters
Authorization: Bearer {{token}}

###

# @name getOneEncounter
GET {{baseUrl}}/api/encounters/{{id}}
Authorization: Bearer {{token}}
