### Feature Patient — GET ALL / GET ONE
### Leyenda: SIN AUTH (sin middleware JWT / sin autenticación)
@baseUrl = http://localhost:4000
@id = 1

# @name getAllPatients
GET {{baseUrl}}/api/patients

###

# @name getOnePatient
GET {{baseUrl}}/api/patients/{{id}}
