### Feature Patient — CREATE
### Leyenda: JWT + RBAC (login como admin + Authorization: Bearer)
@baseUrl = http://localhost:4000

# @name loginAdmin
POST {{baseUrl}}/api/session/login
Content-Type: application/json

{
  "identifier": "admin",
  "password": "Admin123!"
}

@token = {{loginAdmin.response.body.$.access_token}}

###

# @name createPatient
POST {{baseUrl}}/api/patients
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "document_type": "CC",
  "document_number": "1001234567",
  "name": "Ana Pérez",
  "birth_date": "1992-03-15",
  "contact": "3001234567",
  "status": "active"
}
